package typo.ranking.server.server;

import java.util.HashSet;
import java.util.Set;

public class NameGenerator {
	
	private static String[] sAdjectives1 = new String[] { // 35 
//			"Big",
//			"Small",
//			"Red",
//			"Green",
//			"Blue",
//			"Black",
//			"White",
//			"Yellow",
//			"Orange",
//			"Purple",
//			"Old",
//			"Young",
//			"Strong",
//			"Ugly",
//			"Dark",
//			"Light",
//			"Weak",
//			"Tiny",
//			"Fast",
//			"Slow",
//			"Beautiful",
//			"Glamorous",
//			"Copper",
//			"Silver",
//			"Golden",
//			"Rich",
//			"Poor",
//			"Short",
//			"Bald",
//			"Crippled",
//			"Mute",
//			"Deaf",
//			"Blind",
//			"Tall",
//			"Burning",
//			"Ancient",
//			"Pretty",
//			"Royal",
//			"Sick",
//			"Gorgeous",
//			"Handsome",
//			"Athletic",

			"Cold",
			"Warm",
			"Dangerous",
			"Harmless",
			"Benign",
			"Innocuous",
			"Fiery",
			"Angry",
			"Capricious",
			"Violent",
			"Deadly",
			"Lucky",
			"Curious",
			"Confident",
			"Mad",
			"Nervous",
			"Creative",
			"Curly",
			"Sarcastic",
			"Sleepy",
			"Springy",
			"Happy",
			"Clumsy",
			"Cowardly",
			"Nefarious",
			"Articulate",
			"Bright",
			"Calm",
			"Ambitious",
			"Adventurous",
			"Conceited",
			"Clever",
			"Daring",
			"Defiant",
			"Demanding",
			"Devout",
			"Disgruntled",
			"Efficient",
			"Energetic",
			"Funny",
			"Friendly",
			"Frustrated",
			"Fancy",
			"Gentle",
			"Generous",
			"Gracious",
			"Humble",
			"Helpful",
			"Honest",
			"Impulsive",
			"Intelligent",
			"Inventive",
			"Independent",
			"Joyful",
			"Judgemental",
			"Keen",
			"Kind",
			"Lazy",
			"Likeable",
			"Loyal",
			"Loving",
			"Manipulative",
			"Mature",
			"Merry",
			"Messy",
			"Mischievous",
			"Naive",
			"Neat",
			"Noisy",
			"Obnoxious",
			"Organized",
			"Passive",
			"Patient",
			"Patriotic",
			"Pitiful",
			"Pleasant",
			"Pleasing",
			"Popular",
			"Proud",
			"Pious",
			"Radical",
			"Rebellious",
			"Agressive",
			"Quiet",
			"Lethargic",
			"Reliable",
			"Relaxed",
			"Reserved",
			"Respectful",
			"Reverent",
			"Rigid",
			"Rude",
			"Sad",
			"Selfish",
			"Sensible",
			"Sensitive",
			"Serious",
			"Shy",
			"Silly",
			"Simple",
			"Smart",
			"Stubborn",
			"Studious",
			"Tense",
			"Thoughtful",
			"Timid",
			"Tireless",
			"Tolerant",
			"Tough",
			"Tricky",
			"Trusting",
			"Unhappy",
			"Unlucky",
			"Vain",
			"Wild",
			"Wise",
			"Witty",
			"Bold",
			"Lame",
			"Tame",
			"Murderous",
			"Vigilant",
			"Raging",
			"Philandering",
			"Responsible",
			"Wicked",
			"Touchy",
			"Talented",
			"Strange",
			"Spoiled",
			"Stingy",
			"Sly",
			"Sharp",
			"Strict",
			"Sneaky",
			"Secretive",
			"Rowdy",
			"Proper",
			"Rational",
			"Polite",
			"Obidient",
			"Miserable",
			"Mysterious",
			"Lively",
			"Innocent",
			"Industrious",
			"Impolite",
			"Impatient",
			"Ignorant",
			"Hopeless",
			"Hateful",
			"Grumpy",
			"Grouchy",
			"Graceful",
			"Grateful",
			"Gloomy",
			"Fair",
			"Evil",
			"Eager",
			"Dull",
			"Dishonest",
			"Determined",
			"Depressed",
			"Decisive",
			"Cruel",
			"Corageous",
			"Considerate",
			"Confused",
			"Childlish",
			"Brilliant",
			"Brainy",
			"Bad",
			"Average",
			"Attentive",
			"Arrogant",
			"Apologetic",
			"Anxious",
			"Annoyed",
			"Alert",
			"Active",
			"Able",
			"",
	};
	
	private static String[] sAdjectives2=new String[] { // 24
			"River",
			"Sky",
			"Earth",
			"Swamp",
			"Mountain",
			"Sea",
			"Lake",
			"Ravine",
			"Forest",
			"Plains",
			"Hill",
			"Volcano",
			"Waterfall",
			"Cave",
			"Sunset",
			"Desert",
			"Canyon",
			"Land",
			"Night",
			"Morning",
			"Dawn",
			"Moon",
			"Wind",
			"Storm",
			"Hurricane",
			"Fog",
			"Smoke",
			"Sun",
			"Star",
			"Cloud",
			"Mist",
			"Rain",
			"Dune",
			"Puddle",
			"Thundra",
			"Arctic",
			"Stream",
			"Grove",
			"Grass",
			"Mud",
			"Paradise",
			"Snow",
			"",

//			"Fire",
//			"Ice",

//			"Mine",
//			"Castle",
//			"Farm",
//			"Harbor",
//			"Academy",
//			"Fort",
//			"Ruin",
//			"Camp",
//			"Mill",
//			"Dock",
//			"City",
//			"Rural",
//			"Undead",
//			"Field",
//			"Rebel",
//			"Guardian",
//			"War",
	};
	
	private static String[] sAnimals = new String[] { // 30
//			"Dolphin",
//			"Lobster",
//			"Shark",
//			"Whale",
//			"Octopus",
			
			"Bison",
			"Rhino",
			"Hippo",
			"Eagle",
			"Hawk",
			"Pony",
			"Ape",
			"Puppy",
			"Kitten",
			"Monkey",
			"Cow",
			"Deer",
			"Duck",
			"Rabbit",
			"Spider",
			"Wolf",
			"Turkey",
			"Lion",
			"Pig",
			"Raccoon",
			"Otter",
			"Sheep",
			"Lamb",
			"Tapir",
			"Viper",
			"Anaconda",
			"Cobra",
			"Crow",
			"Antelope",
			"Gazelle",
			"Buffalo",
			"Squirrel",
			"Hamster",
			"Bear",
			"Chicken",
			"Ant",
			"Horse",
			"Cat",
			"Dog",
			"Mouse",
			"Firefly",
			"Butterfly",
			"Mosquito",
			"Tiger",
			"Owl",
			"Fox",
			"Panda",
			"Turtle",
			"Coyote",
			"Reindeer",
			"Kangaroo",
			"Hedgehog",
			"Crocodile",
			"Zebra",
			"Hyena",
			"Dingo",
			"Wombat",
			"Weasel",
			"Ferret",
			"Swan",
			"Jaguar",
			"Puma",
			"Cheetah",
			"Raven",
			"Sloth",
			"Chameleon",
			"Bat",
			"Goat",
			"Pigeon",
			"Leopard",
			"Bull",
			"Frog",
			"Condor",
			"Seagull",
			"Goose",
			"Rat",
			"Poodle",
			"Opossum",
			"Scorpion",
			"Yak",
			"Skunk",
			"Lemming",
			"Elephant",
			"Giraffe",
			"Python",
			"Seal",
			"Vulture",
			"Iguana",
			"Colibri",
			"Penguin",
			"Cockroach",
			"Beetle",
			"Koala",
			
//			"Troll",
//			"Slime",
//			"Dragon",
			
		};
		
	
	public static String get() {
		String a1=sAdjectives1[ (int)( Math.random() * sAdjectives1.length ) ];
		String a2=sAdjectives2[ (int)( Math.random() * sAdjectives2.length ) ];
		String a3=sAnimals[ (int)( Math.random() * sAnimals.length ) ];
		return a1+a2+a3;
	}
	
	public static void main(String[] pArg) {
		Set<String> all=new HashSet<String>();
		for( String[] list : new String[][] { sAdjectives1 , sAdjectives2 , sAnimals } ) {
			for( String s : list ) {
				if( all.contains( s )) {
					System.out.println( "duplicate : " + s );
				}
				all.add( s );
			}
			all.clear();
		}
		System.out.println( sAdjectives1.length + " * " + sAdjectives2.length + " * " + sAnimals.length + " = " + sAdjectives1.length * sAdjectives2.length * sAnimals.length );
		for( int i=0 ; i<20 ; ++i ){
			System.out.println( get() );
		}
	}
	
}
